### ISSUE TITLE
[BUG] Bite (Drake Companion)

### ISSUE THREAD

**Issue by Elfrey** [chrisk123999/chris-premades#144]
Bite Attack on Drake Companion gets additional +@prof, because it added in Attack Modifier.
Example on 3rd level ranger.
![image](https://github.com/chrisk123999/chris-premades/assets/519766/34105b53-566e-4409-9a3e-8d3bd04e66e9)

![image](https://github.com/chrisk123999/chris-premades/assets/519766/70914b79-dd3d-4567-9986-27f1d9368c3f)

**Comment by MotoMoto1234** [comment]
I don't think he does these that way.  His equation is actually uniquely different because typically the strategy in these styles of converting Actor A's prof into Actor B's attack is you have to clear actor B's prof out.  So it makes the attack look ugly as you will see -Bmod -Bprof +Amod +Aprof

What he does with these instead is he looks at the difference between the ranger and the drake wardens attack mods and instead of minusing both and adding in the new ones, he takes the difference and applies it as a third modifier to the drake wardens attack.  So it may look like a second prof, but what it should be is 2 is the mod, 3 is the prof, and 2 is the difference, so the ranger probably has a proficiency of 5.  Or I might be mixing up the numbers and its 2 prof, 3 mod, and that 2 is the difference of a ranger with 4 prof and the drake only having 2 prof.

**Comment by Elfrey** [comment]
I couldn't find any other summon with attack defined like that. And in attack roll cleary seen +7 instead of +5 (that should be on 3rd level)

**Comment by MotoMoto1234** [comment]
is this summon draconic spirit or drake warden companion?

**Comment by Elfrey** [comment]
drake warden

**Comment by MotoMoto1234** [comment]
If you need an immediate fix, unlock the cpr compendium "CPR Summon Features" and find the folder for Drake Companion and edit out the `@prof` in the attack roll bonus field:

![image](https://github.com/chrisk123999/chris-premades/assets/116308065/0000f21e-4c89-4764-8584-f24d62e467e9)
![image](https://github.com/chrisk123999/chris-premades/assets/116308065/d7812575-826b-482e-a7f0-cb99554d5d9e)


I have already submitted a bug report to Chris about this.

**Comment by Elfrey** [comment]
I fixed it in my games, just wanted to report so other won't be confused.
Thank you.

**Comment by MotoMoto1234** [comment]
I misidentified this as the other drake summons, the spell at first
