### ISSUE TITLE
3.0 compatible ETA

### ISSUE THREAD

**Issue by belkasro** [chrisk123999/chris-premades#189]
Not asking to rush and thankful for making this bu any idea you think it could be ready?

**Comment by YenBenGrey** [comment]
Unfortunately, due to Chris Premades being reliant on various other modules that Chris doesn't have any control over, there is no way he could tell you any kind of ETA. Unless each reliant module has told Chris when they will be ready, which would be amazing. 

The biggy is MidiQol and Tim has given a timeline of about 2-3 weeks.
